version: 2.1

executors:
  defaults_typescript:
    docker:
      - image: circleci/node:10.13.0
  defaults_api-platform:
    docker:
      - image: chialab/php:7.2
      - image: circleci/postgres:9.6-alpine-ram
    environment:
      - POSTGRES_DB=seed
      - POSTGRES_USER=seed
      - POSTGRES_PASSWORD=Ge0rgesMoustaki

commands:
  yarn-install:
    parameters:
      workspace:
        type: string
    steps:
      - checkout
      - attach_workspace:
          at: ~/keiko/<< parameters.workspace >>
      - restore_cache:
          key: node-modules-cache-{{ checksum "<< parameters.workspace >>/yarn.lock" }}
      - run:
          working_directory: << parameters.workspace >>
          name: Install front dependencies
          command: yarn
      - run:
          working_directory: << parameters.workspace >>
          name: Install bundle size
          command: yarn add bundlesize --save-dev
      - save_cache:
          key: node-modules-cache-{{ checksum "<< parameters.workspace >>/yarn.lock" }}
          paths:
            - << parameters.workspace >>/node_modules
      - persist_to_workspace:
          root: ~/keiko/<< parameters.workspace >>
          paths:
            - node_modules
            - .env

  yarn-tests:
    parameters:
      workspace:
        type: string
    steps:
      - checkout
      - attach_workspace:
          at: ~/keiko/<< parameters.workspace >>
      - run:
          working_directory: << parameters.workspace >>
          name: Unit test with coverage
          command: yarn test:coverage
      - store_artifacts:
          path: << parameters.workspace >>/coverage
      - run:
          working_directory: << parameters.workspace >>
          name: Run Typescript checker
          command: yarn tsc

  yarn-linter:
    parameters:
      workspace:
        type: string
    steps:
      - checkout
      - attach_workspace:
          at: ~/keiko/<< parameters.workspace >>
      - run:
          working_directory: << parameters.workspace >>
          name: Run linter
          command: yarn lint
      - store_artifacts:
          path: << parameters.workspace >>/coverage

jobs:
  composer-install:
    executor: defaults_api-platform
    working_directory: ~/keiko
    steps:
      - checkout
      - attach_workspace:
          at: ~/keiko/backend
      - restore_cache:
          key: composer-cache-{{ checksum "backend/composer.lock" }}
      - run:
          working_directory: backend
          name: Copy env file
          command: cp .env.dist .env
      - run:
          working_directory: backend
          name: Install composer dependencies
          command: composer install -n --prefer-dist
      - save_cache:
          key: composer-cache-{{ checksum "backend/composer.lock" }}
          paths:
            - backend/vendor
      - persist_to_workspace:
          root: ~/keiko/backend
          paths:
            - vendor
            - .env

  api-platform-static-tests:
    executor: defaults_api-platform
    working_directory: ~/keiko
    steps:
      - checkout
      - attach_workspace:
          at: ~/keiko/backend
      - restore_cache:
          key: composer-cache-{{ checksum "backend/composer.lock" }}
      - run:
          working_directory: backend
          name: Run static analysis
          command: ./vendor/bin/phpstan analyse src

  api-platform-functional-tests:
    executor: defaults_api-platform
    working_directory: ~/keiko
    steps:
      - checkout
      - attach_workspace:
          at: ~/keiko/backend
      - restore_cache:
          key: composer-cache-{{ checksum "backend/composer.lock" }}
      - restore_cache:
          key: phpunit-cache-{{ checksum "backend/composer.lock" }}
      - run:
          working_directory: backend
          name: Run migrations
          command: bin/console do:mi:mi --no-interaction --env=test
      - run:
          working_directory: backend
          name: Run functional tests
          command: bin/phpunit --configuration phpunit.xml.circle --testsuite Functional tests
      - save_cache:
          key: phpunit-cache-{{ checksum "backend/composer.lock" }}
          paths:
            - backend/bin/.phpunit
      - persist_to_workspace:
          root: ~/keiko/backend
          paths:
            - bin/.phpunit

  api-platform-linter:
    executor: defaults_api-platform
    working_directory: ~/keiko
    steps:
      - checkout
      - attach_workspace:
          at: ~/keiko/backend
      - restore_cache:
          key: composer-cache-{{ checksum "backend/composer.lock" }}
      - run:
          working_directory: backend
          name: Run static analysis
          command: ./vendor/bin/php-cs-fixer fix --config=./.php_cs.dist --dry-run -v

  yarn-install-front:
    executor: defaults_typescript
    working_directory: ~/keiko
    steps:
      - yarn-install:
          workspace: frontend

  react-tests:
    executor: defaults_typescript
    working_directory: ~/keiko
    environment:
      NODE_ENV: test
    steps:
      - yarn-tests:
          workspace: frontend

  react-bundlesize:
    executor: defaults_typescript
    working_directory: ~/keiko
    environment:
      NODE_ENV: prod
    steps:
      - checkout
      - attach_workspace:
          at: ~/keiko/frontend
      - run:
          working_directory: frontend
          name: Check bundle size
          command: yarn build && ./node_modules/.bin/bundlesize
      - store_artifacts:
          path: frontend/coverage

  react-linter:
    executor: defaults_typescript
    working_directory: ~/keiko
    environment:
      NODE_ENV: prod
    steps:
      - yarn-linter:
          workspace: frontend
      - run:
          working_directory: frontend
          name: Run css linter
          command: yarn lint-style
      - store_artifacts:
          path: frontend/coverage

  e2e-tests:
    machine:
      image: circleci/classic:201808-01
    environment:
      - TERM: xterm
    working_directory: ~/keiko
    steps:
      - checkout
      - restore_cache:
          name: Restore node modules cache
          key: node-modules-e2e-cache-{{ checksum "frontend/package-lock.json" }}
      - restore_cache:
          name: Restore Docker cache
          key: >
            docker-e2e-cache-
            {{ checksum "docker-compose.yml" }}
            {{ checksum "backend/docker/nginx/conf.d/default.conf" }}
            {{ checksum "backend/docker/php.ini" }}
            {{ checksum "backend/docker/varnish/default.vcl" }}
      - run:
          name: Load stored Docker images
          command: |
            if [ -d docker_images ]; then
              docker load < docker_images/varnish.tar
              docker load < docker_images/nginx.tar
              docker load < docker_images/php.tar
              docker load < docker_images/psql.tar
            fi
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.23.2/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          working_directory: backend
          name: Create env file
          command: |
            cp .env.dist .env
            echo "DATABASE_URL=postgres://seed:Ge0rgesMoustaki@db-test/seed" >> .env
      - run:
          working_directory: backend
          name: Copy test JWT keys
          command: |
            echo "JWT_PASSPHRASE=lolilol" >> .env
            cp tests/jwt/* config/jwt
      - run:
          name: Start backend
          command: docker-compose up -d
      - run:
          working_directory: frontend
          name: Setup Dependencies
          command: yarn install
      - run:
          name: Load fixtures
          command: docker-compose exec php bin/console hautelook:fixtures:load -n
      - run:
          working_directory: frontend
          name: Run e2e tests
          command: |
            export NVM_DIR="/opt/circleci/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
            nvm use 10.8
            yarn start &
            $(npm bin)/wait-on http://localhost:3000
            $(npm bin)/cypress run
      - store_artifacts:
          path: frontend/cypress/videos
      - save_cache:
          name: Save node modules cache
          key: node-modules-e2e-cache-{{ checksum "frontend/package-lock.json" }}
          paths:
            - frontend/node_modules
            - ~/.npm
            - ~/.cache
      - run:
          name: Save Docker images
          command: |
            mkdir -p docker_images
            source .env
            docker save ${CONTAINER_REGISTRY_BASE}/varnish > docker_images/varnish.tar
            docker save ${CONTAINER_REGISTRY_BASE}/nginx > docker_images/nginx.tar
            docker save ${CONTAINER_REGISTRY_BASE}/php > docker_images/php.tar
            docker save postgres:10.6-alpine > docker_images/psql.tar
      - save_cache:
          name: Save Docker cache
          key: docker-e2e-cache-{{ checksum "docker-compose.yml" }}
          paths:
            - docker_images

workflows:
  version: 2
  stack:
    jobs:
      - composer-install
      - api-platform-linter:
          requires:
            - composer-install
      - api-platform-static-tests:
          requires:
            - composer-install
      - api-platform-functional-tests:
          requires:
            - composer-install
      - yarn-install-front
      - react-tests:
          requires:
            - yarn-install-front
      - react-bundlesize:
          requires:
            - yarn-install-front
      - react-linter:
          requires:
            - yarn-install-front
      - e2e-tests
